@echo off 

:: CHANGE THESE PATHS
set "MAYA_HOME=C:\"Program Files"\Autodesk\Maya2018"
set "ARNOLD_INSTALL_PATH=C:\solidangle\mtoadeploy\2018.3.1.wip"
set "TRUNK=D:\WORK\Development\Dev\trunk"


:: MTOA RELEVANT PATHS 
set "ARNOLD_PLUGIN_PATH=%ARNOLD_INSTALL_PATH%\plug-ins"
set "PATH=%PATH%;%ARNOLD_INSTALL_PATH%\bin"

:: SETTING USER PATHS
set "OSL_PATH=%TRUNK%\lightshader\osl"

:: SETTING MAYA PATHS
set "ARNOLD_PLUGIN_PATH=%ARNOLD_PLUGIN_PATH%;%OSL_PATH%;"
set "MTOA_TEMPLATES_PATH=%MTOA_TEMPLATES_PATH%"
set "MAYA_MODULE_PATH=%MAYA_MODULE_PATH%;%ARNOLD_INSTALL_PATH%;%TRUNK%\lightshader\maya;"
set "MAYA_RENDER_DESC_PATH=%ARNOLD_INSTALL_PATH%"
set "PYTHONPATH=%PYTHONPATH%;%TRUNK%"

"%KATANA_HOME%\bin\maya.exe"

